init:
  position:
    x: 0.691949695095547
    y: -1.395750757746275
    z: 312.2643980319930

  velocity:
    x: 0.0
    y: 0.0
    z: 0.0

  orientation:
    x: 0.0
    y: 0.0
    z: 1.4835

  bias:
    accel:
      x: 0.0
      y: 0.0
      z: 0.0
    gyro:
      x: 0.0
      y: 0.0
      z: 0.0

imu:
  publish_hz: 250
  sensor_pub_rate: 250
  topic: /imu/dataAdis
  noise:
    sig_gyro_inRun : 7.757018897752577e-06
    sig_ARW : 2.908882086657216e-05
    sig_accel_inRun : 3.139200000000000e-05
    sig_VRW : 1.333333333333333e-04


odo:
  topic: /husky_velocity_controller/odom
  updates:
    do_zupt: false
    do_zaru: false


joint:
  topic: /joint_states

frames:
  frame_id_out: map
  frame_id_fixed: odom
  frame_id_imu: imu_link
  frame_id_odo: odom_link

wheel:
  T_r_: 0.125
  s_or_: 0.0
  s_delta_or_: 0.0
